// AUTO-GENERATED by scripts/generate-nav.mjs — do not edit by hand.
// Re-run `node scripts/generate-nav.mjs` after adding or removing routes.
export const navLinks = [
  { href: '/', label: 'Dashboard' },
  { href: '/deploy', label: 'Deploy' },
  { href: '/deployments', label: 'Deployments' },
] as const;
