// Build-time nav generator.
//
// Scans app/ for page.tsx files, derives routes and labels, and writes
// lib/navConfig.ts. Run via: node scripts/generate-nav.mjs
//
// Skipped automatically:
//   - Dynamic segments: [param], [...slug], [[...slug]]
//   - Private folders: _name (Next.js convention)
//   - Route groups:    (group) — transparent to URL, stripped when computing href
//   - API routes:      app/api/**
//   - Detail pages:    any segment containing a dynamic param anywhere in the path
//
// To exclude a specific route from the nav, add it to EXCLUDED_ROUTES below.

import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = join(__dirname, '..');
const APP_DIR   = join(ROOT, 'app');
const OUT_FILE  = join(ROOT, 'lib', 'navConfig.ts');

// Routes to exclude from the generated nav even if they have a page.tsx.
const EXCLUDED_ROUTES = new Set([
  // '/example',
]);

// Segment matchers.
const isDynamic     = (seg) => seg.startsWith('[');
const isPrivate     = (seg) => seg.startsWith('_');
const isRouteGroup  = (seg) => seg.startsWith('(') && seg.endsWith(')');
const isApiRoute    = (seg) => seg === 'api';

function toLabel(segment) {
  // 'new-demo' → 'New Demo', 'deploy' → 'Deploy'
  return segment
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function collectRoutes(dir, urlSegments = []) {
  const routes = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  // Does this directory itself have a page?
  const hasPage = entries.some(
    (e) => e.isFile() && (e.name === 'page.tsx' || e.name === 'page.ts')
  );

  if (hasPage && urlSegments.length > 0) {
    // Dynamic anywhere in the path → skip (detail pages, catch-alls)
    const hasDynamic = urlSegments.some(isDynamic);
    if (!hasDynamic) {
      const href = '/' + urlSegments.join('/');
      if (!EXCLUDED_ROUTES.has(href)) {
        const labelSegment = [...urlSegments].reverse().find((s) => !isRouteGroup(s)) ?? urlSegments.at(-1);
        routes.push({ href, label: toLabel(labelSegment) });
      }
    }
  }

  // Recurse into subdirectories.
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const seg = entry.name;
    if (isPrivate(seg) || isApiRoute(seg)) continue;

    // Route groups don't add a URL segment.
    const nextSegments = isRouteGroup(seg)
      ? urlSegments
      : [...urlSegments, seg];

    routes.push(...collectRoutes(join(dir, seg), nextSegments));
  }

  return routes;
}

// The root page (app/page.tsx) is always first.
const rootEntries = readdirSync(APP_DIR, { withFileTypes: true });
const hasRootPage = rootEntries.some(
  (e) => e.isFile() && (e.name === 'page.tsx' || e.name === 'page.ts')
);

const routes = [
  ...(hasRootPage ? [{ href: '/', label: 'Dashboard' }] : []),
  ...collectRoutes(APP_DIR),
];

const banner = [
  '// AUTO-GENERATED by scripts/generate-nav.mjs — do not edit by hand.',
  '// Re-run `node scripts/generate-nav.mjs` after adding or removing routes.',
].join('\n');

const body = routes
  .map(({ href, label }) => `  { href: '${href}', label: '${label}' },`)
  .join('\n');

const output = `${banner}\nexport const navLinks = [\n${body}\n] as const;\n`;

writeFileSync(OUT_FILE, output, 'utf8');
console.log(`Generated ${OUT_FILE}:`);
routes.forEach(({ href, label }) => console.log(`  ${href.padEnd(20)} → ${label}`));
