// Build-time locale generator.
//
// Fetches the enabled language branches from the Optimizely CMS Management API
// and writes `lib/locales.generated.ts`, the single source of truth consumed by
// proxy.ts, the catch-all page, and the language switcher.
//
// Run via: `npm run gen:locales` (which passes `--env-file=.env`).
//
// Auth + endpoints mirror the cms-cli's REST client
// (node_modules/@optimizely/cms-cli/dist/service/cmsRestClient.js): OAuth
// client-credentials → `POST {gateway}/oauth/token`, then `GET {gateway}/v1/locales`.
//
// Resilience: if credentials are missing or any request fails, we WARN and emit a
// fallback file containing only the default locale, so builds/CI without CMS
// access still succeed.

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_FILE = join(ROOT, 'lib', 'locales.generated.ts');

// Resolve configuration from the environment. On Vercel/CI the vars are injected
// by the platform (already in process.env). Locally they often aren't exported,
// so if the CMS credentials are missing we fall back to loading the project's
// .env file. `process.loadEnvFile` does not overwrite vars already in the
// environment, so the platform's values always win.
if (
  (!process.env.OPTIMIZELY_CMS_CLIENT_ID || !process.env.OPTIMIZELY_CMS_CLIENT_SECRET) &&
  typeof process.loadEnvFile === 'function'
) {
  try {
    process.loadEnvFile(join(ROOT, '.env'));
    console.log('[gen:locales] Loaded configuration from .env');
  } catch {
    // No .env file present — continue with whatever is already in process.env.
  }
}

const GATEWAY = (process.env.OPTIMIZELY_CMS_API_URL || 'https://api.cms.optimizely.com').replace(
  /\/$/,
  '',
);
const DEFAULT_LOCALE = process.env.OPTIMIZELY_DEFAULT_LOCALE || 'en';
const { OPTIMIZELY_CMS_CLIENT_ID, OPTIMIZELY_CMS_CLIENT_SECRET } = process.env;

/** @typedef {{ key: string, displayName: string, routeSegment: string }} Locale */

async function getToken() {
  const res = await fetch(`${GATEWAY}/oauth/token`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      grant_type: 'client_credentials',
      client_id: OPTIMIZELY_CMS_CLIENT_ID,
      client_secret: OPTIMIZELY_CMS_CLIENT_SECRET,
    }),
  });
  if (!res.ok) {
    throw new Error(`Token request failed: ${res.status} ${res.statusText}`);
  }
  const data = await res.json();
  if (!data?.access_token) throw new Error('Token endpoint returned no access_token');
  return data.access_token;
}

/** @returns {Promise<Locale[]>} */
async function fetchLocales(token) {
  const res = await fetch(`${GATEWAY}/v1/locales?pageSize=100`, {
    headers: { authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`Locales request failed: ${res.status} ${res.statusText}`);
  }
  const data = await res.json();
  const items = Array.isArray(data?.items) ? data.items : [];
  return items
    .filter((l) => l.isEnabled !== false)
    .sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
    .map((l) => ({
      key: l.key,
      displayName: l.displayName ?? l.key,
      // The default locale serves clean URLs (no segment), regardless of what the
      // CMS reports, so proxy.ts can strip/redirect it consistently.
      routeSegment: l.key === DEFAULT_LOCALE ? '' : l.routeSegment ?? l.key,
    }));
}

function fallbackLocales() {
  return [{ key: DEFAULT_LOCALE, displayName: 'English', routeSegment: '' }];
}

/** Print a readable summary of the locales written to the generated file. */
function printLocales(locales) {
  console.log(`[gen:locales] ${locales.length} locale(s) written:`);
  const keyWidth = Math.max(...locales.map((l) => l.key.length));
  for (const l of locales) {
    const routing =
      l.key === DEFAULT_LOCALE ? 'default locale — clean URLs (no prefix)' : `URLs under /${l.routeSegment}/`;
    console.log(`  • ${l.key.padEnd(keyWidth)}  ${l.displayName} — ${routing}`);
  }
}

function render(locales) {
  return `// AUTO-GENERATED by scripts/generate-locales.mjs — do not edit.
// Run \`npm run gen:locales\` to refresh. Source: Optimizely CMS Management API /locales.

export type Locale = {
  /** BCP-47 language tag, e.g. "en", "es", "sv-SE". */
  key: string;
  /** Human-readable name shown in the language switcher. */
  displayName: string;
  /** URL segment for routing. Empty string for the default locale (clean URLs). */
  routeSegment: string;
};

export const DEFAULT_LOCALE = ${JSON.stringify(DEFAULT_LOCALE)};

export const LOCALES: Locale[] = ${JSON.stringify(locales, null, 2)};
`;
}

async function main() {
  let locales;
  try {
    if (!OPTIMIZELY_CMS_CLIENT_ID || !OPTIMIZELY_CMS_CLIENT_SECRET) {
      throw new Error(
        'Missing OPTIMIZELY_CMS_CLIENT_ID / OPTIMIZELY_CMS_CLIENT_SECRET',
      );
    }
    const token = await getToken();
    locales = await fetchLocales(token);
    if (!locales.length) throw new Error('CMS returned no enabled locales');
    console.log(`[gen:locales] Fetched locales from the CMS.`);
  } catch (err) {
    console.warn(
      `[gen:locales] Falling back to default locale "${DEFAULT_LOCALE}" — ${err.message}`,
    );
    locales = fallbackLocales();
  }

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, render(locales), 'utf8');
  printLocales(locales);
  console.log(`[gen:locales] Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error('[gen:locales] Unexpected error:', err);
  process.exit(1);
});
